# Generated by Django 3.0.7 on 2020-07-21 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200614_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
