# Generated by Django 3.0.7 on 2020-07-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200721_1551'),
        ('users', '0003_profile_premium_date'),
    ]

    operations = [
    ]
