# Generated by Django 3.0.4 on 2020-06-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
