# Generated by Django 3.0.4 on 2020-04-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('data_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=30)),
                ('translation', models.CharField(max_length=30)),
                ('last_viewed_time', models.DateTimeField(auto_now=True, verbose_name='date reviewed')),
                ('last_time_remembered', models.BooleanField(default=False)),
                ('times_remembered', models.IntegerField(default=0)),
                ('times_failed', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.MovieSet')),
            ],
        ),
    ]
