# Generated by Django 3.0.4 on 2020-04-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20200426_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieset',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
